# Generated by Django 5.2.15 on 2026-06-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionJournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pompiste_id', models.IntegerField()),
                ('pompiste_nom', models.CharField(max_length=100)),
                ('station_id', models.IntegerField()),
                ('station_nom', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='en_cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VenteSimulee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carburant', models.CharField(max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(default='especes', max_length=20)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('code_validation', models.CharField(blank=True, max_length=6, null=True)),
                ('statut', models.CharField(default='en_cours', max_length=20)),
                ('vente_id_anw', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pompe.sessionjournee')),
            ],
        ),
    ]
