# Generated by Django 5.2.15 on 2026-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventesimulee',
            name='synchronise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventesimulee',
            name='tentative_sync',
            field=models.IntegerField(default=0),
        ),
    ]
