# Generated by Django 5.2.15 on 2026-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0002_ventesimulee_synchronise_ventesimulee_tentative_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionjournee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sessionjournee',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
